tunnel: cognio-agent-tunnel
credentials-file: ~/.cloudflared/cert.json

ingress:
  - hostname: api.vaani.pro
    service: http://localhost:8000
    originRequest:
      noTLSVerify: true
    headers:
      - name: Access-Control-Allow-Origin
        value: "https://www.vaani.pro"
      - name: Access-Control-Allow-Methods
        value: "GET, POST, PUT, DELETE, OPTIONS"
      - name: Access-Control-Allow-Headers
        value: "Content-Type, Authorization"

  # Catch-all rule
  - service: http_status:404

# Additional security headers
headers:
  request:
    - name: X-Real-IP
      value: ${CF-CONNECTING-IP}
  response:
    - name: Strict-Transport-Security
      value: max-age=31536000; includeSubDomains; preload
    - name: X-Content-Type-Options
      value: nosniff
    - name: X-Frame-Options
      value: DENY
