name = "cognio-agent-api"
compatibility_date = "2024-03-27"

# This tells Cloudflare Pages where to find your built files
pages_build_output_dir = "."

# CORS headers for Pages - this is the correct format
[[build.upload.rules]]
type = "Headers"
globs = ["/*"]
headers = {Access-Control-Allow-Origin = "https://vanni-test-frontend.vercel.app", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS", Access-Control-Allow-Headers = "Content-Type, Authorization", Access-Control-Max-Age = "86400"}