name = "cognio-agent-api"
compatibility_date = "2024-03-27"
main = "worker.js"

# Use current directory as output
pages_build_output_dir = "."

[build]
command = "chmod +x build.sh && ./build.sh"

[site]
bucket = "."

# Headers for CORS
[[routes]]
pattern = "/*"
zone_name = "yoursite.com"
custom_domain = true
[[routes.headers]]
name = "Access-Control-Allow-Origin"
value = "https://vanni-test-frontend.vercel.app"
[[routes.headers]]
name = "Access-Control-Allow-Methods"
value = "GET, POST, PUT, DELETE, OPTIONS"
[[routes.headers]]
name = "Access-Control-Allow-Headers"
value = "Content-Type, Authorization"
[[routes.headers]]
name = "Access-Control-Max-Age"
value = "86400"