name = "cognio-agent-api"
compatibility_date = "2024-03-27"
workers_dev = true

[build]
command = "chmod +x build.sh && ./build.sh"
output_dir = "dist"

# Set this to match output_dir
pages_build_output_dir = "dist"

[vars]
ENVIRONMENT = "production"

# Configure CORS - use this proper format for Pages
[[headers]]
pattern = "/*"
headers = [
  { key = "Access-Control-Allow-Origin", value = "https://vanni-test-frontend.vercel.app" },
  { key = "Access-Control-Allow-Methods", value = "GET, POST, PUT, DELETE, OPTIONS" },
  { key = "Access-Control-Allow-Headers", value = "Content-Type, Authorization" },
  { key = "Access-Control-Max-Age", value = "86400" }
]

[site]
bucket = "./dist"

[build.output]
directory = "dist"