name = "cognio-agent-api"
compatibility_date = "2024-03-27"
workers_dev = true

[build]
command = "chmod +x build.sh && ./build.sh"

[build.upload]
format = "service-worker"

# Environment variables
[vars]
ENVIRONMENT = "production"

# Configure CORS
[[routes]]
pattern = "/*"
[routes.headers]
Access-Control-Allow-Origin = "https://vanni-test-frontend.vercel.app"
Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
Access-Control-Allow-Headers = "Content-Type, Authorization"
Access-Control-Max-Age = "86400"