name = "cognio-agent-api"
compatibility_date = "2024-03-27"
workers_dev = true

[build]
command = "pip install -r requirements.txt && pip install -e . && mkdir -p dist && cp main.py dist/ && cp -r src dist/ && touch dist/requirements.txt"
output_dir = "dist"

[vars]
ENVIRONMENT = "production"

# Configure CORS
[[headers]]
pattern = "/*"
headers = [
  { key = "Access-Control-Allow-Origin", value = "https://vanni-test-frontend.vercel.app" },
  { key = "Access-Control-Allow-Methods", value = "GET, POST, PUT, DELETE, OPTIONS" },
  { key = "Access-Control-Allow-Headers", value = "Content-Type, Authorization" },
  { key = "Access-Control-Max-Age", value = "86400" }
]

pages_build_output_dir = "dist"

[site]
bucket = "./dist"
