name = "cognio-agent-api"
compatibility_date = "2024-03-27"
workers_dev = true

[build]
command = "pip install -r requirements.txt && pip install -e . && mkdir -p dist && cp -r . dist/ && cp main.py dist/index.py"

[site]
bucket = "./dist"

[build.upload]
format = "service-worker"

# The output directory for your build
[build.output]
directory = "dist"

# Environment variables
[vars]
ENVIRONMENT = "production"

# Configure CORS
[[routes]]
pattern = "/*"
[routes.headers]
Access-Control-Allow-Origin = "https://vanni-test-frontend.vercel.app"
Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
Access-Control-Allow-Headers = "Content-Type, Authorization"
Access-Control-Max-Age = "86400"