name = "cognio-agent-api"
compatibility_date = "2024-03-27"
workers_dev = true

[build]
command = "pip install -r requirements.txt"

[vars]
ENVIRONMENT = "production"

# Add your routes
[[routes]]
pattern = "api/*"
script = "api/index.js"

# Configure CORS
[[headers]]
pattern = "/*"
headers = [
  { key = "Access-Control-Allow-Origin", value = "https://vanni-test-frontend.vercel.app" },
  { key = "Access-Control-Allow-Methods", value = "GET, POST, PUT, DELETE, OPTIONS" },
  { key = "Access-Control-Allow-Headers", value = "Content-Type, Authorization" },
  { key = "Access-Control-Max-Age", value = "86400" }
]
